# Generated by Django 4.1.2 on 2024-05-19 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orderitem_price_orderitem_price_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price_currency',
        ),
    ]
