# Generated by Django 4.1.2 on 2024-02-21 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import finance.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_remove_order_address_remove_order_location'),
        ('services', '0002_service_price_service_price_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='Pending', max_length=50)),
                ('county', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('phone_number', finance.models.CustomPhoneNumberField(max_length=128, null=True, region=None)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
            options={
                'verbose_name': 'Order Payment',
                'verbose_name_plural': 'Order Payments',
            },
        ),
        migrations.CreateModel(
            name='BooKingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('address', models.IntegerField()),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_status', models.CharField(choices=[('PN', 'Pending'), ('AP', 'Approved'), ('RJ', 'Rejected'), ('CP', 'Completed')], default='Pending', max_length=50)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('phone_number', finance.models.CustomPhoneNumberField(max_length=128, null=True, region=None)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.servicebooking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Payment',
                'verbose_name_plural': 'Booking Payments',
            },
        ),
    ]
