# Generated by Django 4.1.2 on 2024-03-12 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_bookingpayment_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingpayment',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='bookingpayment',
            name='user',
        ),
    ]
