# Generated by Django 4.1.2 on 2024-03-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_bookingpayment_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpayment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
