# Generated by Django 4.1.2 on 2024-06-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tools_required',
            field=models.TextField(blank=True, null=True),
        ),
    ]
