# Generated by Django 4.1.2 on 2024-05-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignedServiceBooking',
        ),
    ]
