# Generated by Django 4.1.2 on 2024-05-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='location',
            field=models.CharField(choices=[('kitale', 'Kitale'), ('eldoret', 'Eldoret'), ('iten', 'Iten'), ('marigat', 'Marigat'), ('kericho', 'Kericho')], max_length=50),
        ),
    ]
