# Generated by Django 4.1.2 on 2024-03-13 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_installerassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installerassignment',
            old_name='operator',
            new_name='installer',
        ),
        migrations.AlterField(
            model_name='installerassignment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installer_assignment', to='services.servicebooking'),
        ),
    ]
