# Generated by Django 4.1.2 on 2024-06-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_tools_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='tools_required',
            field=models.TextField(blank=True, null=True),
        ),
    ]
