# Generated by Django 4.1.2 on 2024-05-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servicebooking_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='installerassignment',
            name='tools_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installerassignment',
            name='tools_requested',
            field=models.BooleanField(default=False),
        ),
    ]
