# Generated by Django 4.1.2 on 2024-06-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicebooking_tools_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='customer_approval',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='customer_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='service_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
