# Generated by Django 4.1.2 on 2024-05-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='rejection_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('OFD', 'Out For Delivery'), ('DL', 'Delivered'), ('CL', 'Complete'), ('RJ', 'Rejected')], default='PD', max_length=3, verbose_name='status'),
        ),
    ]
